function tbl = flat_ipg_data(path)
% import IPG results as a Table
% opts = delimitedTextImportOptions('DataLines',3,'RowNamesColumn',1,'VariableNamesLine',1,'VariableDescriptionsLine',0,'VariableUnitsLine',0,'Delimiter',{'#','\t'});
opts = detectImportOptions(path);
opts.VariableUnitsLine = 2;
opts.DataLines = 4;
opts.RowNamesColumn = 0;
opts.SelectedVariableNames = opts.SelectedVariableNames(2:end);
% w = warning('query','last');
% warning('off',w.identifier);
tbl = readtable(path,opts);

%% RENAMING THE IPG VARNAMES TO THE VALIDATION NAMES

tbl = tbl(:,{'Time', ...
    'Car_v', ...
    'Car_Distance',...
    'Car_ax', ...
    'PT_Engine_PwrO', ...
    'PT_Engine_rotv', ...
    'Brake_Hyd_CU_Pedal', ...
    'Brake_Hyd_Sys_pMC', ...
    'PT_Engine_FuelFlow', ...
    'PT_GearBox_GearNo', ...
    'Car_Road_Path_LongSlope',...
    'Sensor_Object_RadarL_relvTgt_NearPnt_ds_p', ...
    'AccelCtrl_ACC_Time2Collision',...
    'PwrL_Brake','PwrL_Aero','PwrD_Inert_Chassis','PwrD_Grvt','PwrL_Tire','PT_Engine_be'});

% tbl = removevars(tbl,{'Brake_Hyd_CU_BooSignal', ...
%     'PwrD_Aero_Lift','PwrD_Aero_Pitch','PwrD_Aero_Roll',...
%     'PwrD_Aero_Side','PwrD_Aero_Total','PwrD_Aero_Yaw',...
%     'PwrD_Brake_TotalFL','PwrD_Brake_TotalFR','PwrD_Brake_TotalRL',...
%     'PwrD_Brake_TotalRL2','PwrD_Brake_TotalRR','PwrD_Brake_TotalRR2',...
%     'PwrD_Hitch_Frc_x','PwrD_Hitch_Frc_y','PwrD_Hitch_Frc_z',...
%     'PwrD_Hitch_Total','PwrD_Hitch_Trq_x','PwrD_Hitch_Trq_y','PwrD_Hitch_Trq_z',...
%     'PwrD_PT_Battery_HV','PwrD_PT_Battery_LV','PwrD_PT_CDiff','PwrD_PT_CDiffF','PwrD_PT_CDiffR'
%     });
tbl = renamevars(tbl,{'Time', ...
    'Car_v', ...
    'Car_Distance',...
    'Car_ax', ...
    'PT_Engine_PwrO', ...
    'PT_Engine_rotv', ...
    'Brake_Hyd_CU_Pedal', ...
    'Brake_Hyd_Sys_pMC', ...
    'PT_Engine_FuelFlow', ...
    'PT_GearBox_GearNo', ...
    'Car_Road_Path_LongSlope',...
    'Sensor_Object_RadarL_relvTgt_NearPnt_ds_p', ...
    'AccelCtrl_ACC_Time2Collision'}, ...
    {'time',...
    'v',...
    'x',...
    'a_true',...
    'engine_power',...
    'engine_rpm',...
    'brake_pedal_position',...
    'brake_pressure',...
    'fuel_rate',...
    'gear_number',...
    'grade',...
    'radar_range', ...
    'time_gap'});

tbl = movevars(tbl,{'time',...
    'x',...
    'v',...
    'a_true',...
    'engine_power',...
    'engine_rpm',...
    'brake_pedal_position',...
    'brake_pressure',...
    'fuel_rate',...
    'gear_number',...
    'grade',...
    'radar_range', ...
    'time_gap'},'before','time_gap');

tbl = convert_ipg_units(tbl);

end

