function tbl = flat_auburn_data(path)
% flat_auburn_data
% The purpose of this script is to take the Auburn matfiles and place them
% into a flat format for standard analysis. the Key task of this process
% is the time-alignment of the non-uniform time vectors for each signal
%
% The time_align function perfroms linear interpolation on doubles and
% nearest interpolation on known logicals/integers, although not all
% classes are correct in the auburn matfiles. Take for instance, the
% current gear, which is an integer in reality, but the class of the data is double.
% To deal with this, the known integers are rounded just in case.
% Evan Stegner

%% Data load
% load('F:/ACM_2019_data/4T_100/A2_4T_100_1_2019-10-24-08-23-35.mat')
% load('F:\Patrick Smith\Canada_Fuel_Test\OT\A2\OT-CI-S75-1_2019-06-27-17-18-20.mat')
% load('F:\Patrick Smith\Canada_Fuel_Test\AL\A2\AL-S75-1_2019-06-17-07-38-10.mat')
% load('F:\Patrick Smith\Canada_Fuel_Test\AL\A2\AL-S75-2_2019-06-17-08-41-35.mat')
% load('F:\Patrick Smith\Canada_Fuel_Test\AL\A2\AL-S75-3_2019-06-17-12-55-02.mat')
% load("F:\field_test\bagfiles\A2\test_data\parsed_au_mobile_2T_A2_2022-03-30-09-11-19.mat")
load(path,'data')

%% Base time vector for interpolation:
base_time = data.novatel_local.llhPositionTagged.time;

%% time align other signals
lat = time_align('novatel_local.llhPositionTagged.latitude',data,base_time);
lon = time_align('novatel_local.llhPositionTagged.longitude',data,base_time);
alt = time_align('novatel_local.llhPositionTagged.altitude',data,base_time);
course = time_align('novatel_local.odom.course',data,base_time);
gps_week = time_align('novatel_local.llhPositionTagged.gpsWeek',data,base_time);
gps_seconds = time_align('novatel_local.llhPositionTagged.gpsSeconds',data,base_time);

v = time_align('j1939.vehicle_speed.wheelBasedSpeed',data,base_time);

engine_pct_torque = time_align('j1939.engine_status_1.actualPercentTorque',data,base_time);
engine_rpm = time_align('j1939.engine_status_1.engineSpeed',data,base_time);

brake_by_driver = time_align('j1939.brake_status_1.ebsBrakeSwitch',data,base_time); % on off only driver
brakes_on = time_align('j1939.vehicle_state.brakes',data,base_time); % A general boolean about whether or not the vehicle braked
brake_pedal_position =time_align('j1939.brake_status_1.brakePedalPosition',data,base_time); %sensed brake pedal position, only driver
desired_ctrl_brake_rate = time_align('truck_control.control_diagnostics.brakeRate',data,base_time); % our input

retarder_pct_torque = time_align('j1939.retarder_status_1.actualRetarderPercentTorque',data,base_time);

fuel_rate = time_align('j1939.fuel_economy.fuelRate',data,base_time);
gear_number = round(time_align('j1939.transmission_status_2.currentGear',data,base_time));
fan_state = time_align('j1939.engine_fan.fanDriveState',data,base_time);

grade_estimate = time_align('grade_estimation.gradeEstimate',data,base_time);
range_estimate = time_align('range_estimator.rangeEstimationOutput.range',data,base_time);

try
drtk_v2v_dist = interp1(data.drtk.drtk_output.time,sqrt(sum(data.drtk.drtk_output.rpvDifferentialPseudorange.^2)),base_time,'linear');

catch
    disp('no drtk v2v')
    drtk_v2v_dist = nan(size(base_time));
end


%% Table it!

tbl = table(base_time',...
    lat',...
    lon',...
    alt',...
    course',...
    gps_week',...
    gps_seconds',...
    v',...
    engine_pct_torque',...
    engine_rpm',...
    brake_by_driver',...
    brakes_on',...
    brake_pedal_position',...
    desired_ctrl_brake_rate',...
    retarder_pct_torque',...
    fuel_rate',...
    gear_number',...
    fan_state',...
    grade_estimate',...
    range_estimate',...
    drtk_v2v_dist',...
    'VariableNames',{'time',...
    'lat',...
    'lon',...
    'alt',...
    'course',...
    'gps_week',...
    'gps_seconds',...
    'v',...
    'engine_pct_torque',...
    'engine_rpm',...
    'brake_by_driver',...
    'brakes_on',...
    'brake_pedal_position',...
    'desired_ctrl_brake_rate',...
    'retarder_pct_torque',...
    'fuel_rate',...
    'gear_number',...
    'fan_state',...
    'grade_estimate',...
    'range_estimate',...
    'drtk_v2v_dist'});

%% clean the table
tbl = clean_tbl(tbl);

end

