function NPC_error_plot(X1, Y1,alpha,figure1)
%CREATEFIGURE(X1, Y1)
%  X1:  vector of plot x data
%  Y1:  vector of plot y data

%  Auto-generated by MATLAB on 01-Mar-2024 23:06:30
if ~exist('alpha','var')
    alpha = 1;
end

% Create figure
if ~exist("figure1","var")
    figure1 = figure;
    axes1 = axes('Parent',figure1);
else
    axes1 =gca();
end

% Create axes
    
hold(axes1,'on');

% Create plot
scatter(X1,Y1,'filled','SizeData',5,MarkerFaceAlpha=alpha,MarkerEdgeColor='none');

% Create xline
xline(1,'Parent',axes1);

% Create yline
yline(1,'Parent',axes1);

% Create ylabel
ylabel('NPC');

% Create xlabel
xlabel('NPC_{inferred}');

% Create title
title({'Error in C_d'});

% Uncomment the following line to preserve the X-limits of the axes
xlim(axes1,[0.5 1.5]);
% Uncomment the following line to preserve the Y-limits of the axes
ylim(axes1,[0.5 1.5]);

box(axes1,'on');
hold(axes1,'off');
% Create textbox
annotations = false
if annotations
annotation(figure1,'textbox',...
    [0.150107143522372 0.802380954793535 0.224999993826662 0.104761902349336],...
    'String',{'False positive','on power savings'},...
    'HorizontalAlignment','center',...
    'FaceAlpha',0.6,...
    'BackgroundColor',[1 1 1]);

% Create textbox
annotation(figure1,'textbox',...
    [0.664392857808085 0.133333335745918 0.224999993826662 0.104761902349336],...
    'String',{'False negative','on power savings'},...
    'HorizontalAlignment','center',...
    'FaceAlpha',0.6,...
    'BackgroundColor',[1 1 1]);

% Create textbox
annotation(figure1,'textbox',...
    [0.703678571508394 0.847619048825347 0.185714280711753 0.0642857130794299],...
    'String',{'True negative'},...
    'HorizontalAlignment','center',...
    'FaceAlpha',0.6,...
    'BackgroundColor',[1 1 1]);

% Create textbox
annotation(figure1,'textbox',...
    [0.150999999946781 0.133333334539631 0.176785709549274 0.0642857130794298],...
    'String',{'True positive'},...
    'HorizontalAlignment','center',...
    'FaceAlpha',0.6,...
    'BackgroundColor',[1 1 1]);
end
