clearvars -except tbl
close all
if ~exist('tbl','var')
    load('..\processed\tbl_platoon_working.mat','tbl')
end
rng("default")
addpath('..\functions\')
addpath('..\lookups\truck_params\')
subtbl=tbl(tbl.ID==1500,:);
param_offsets = struct('front_area',-1,'trailer_mass',-2000,'f_rr_c',-0.001);
subtbl = model_acceleration_with_aero_ipg(subtbl);
subtbl_off = model_acceleration_with_aero_ipg(subtbl,param_offsets);

createfigure(subtbl.time,[cumtrapz(subtbl.a_true-subtbl.a_modeled_w_drr)/10,cumtrapz(subtbl.a_true-subtbl_off.a_modeled_w_drr)/10])

function createfigure(X1, YMatrix1)
%CREATEFIGURE(X1, YMatrix1)
%  X1:  vector of plot x data
%  YMATRIX1:  matrix of plot y data

%  Auto-generated by MATLAB on 03-Feb-2024 14:00:47

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple line objects using matrix input to plot
plot1 = plot(X1,YMatrix1);
set(plot1(1),'DisplayName','Correct Parameters');
set(plot1(2),'DisplayName','Incorrect Parameters');

% Create ylabel
ylabel('Integrated Acceleration Error [m/s]');

% Create xlabel
xlabel('Time [s]');

box(axes1,'on');
hold(axes1,'off');
% Create legend
legend1 = legend(axes1,'show');
set(legend1,'AutoUpdate','off','Location','best');

% Create textarrow
annotation(figure1,'textarrow',[0.389285714285713 0.389285714285714],...
    [0.266666666666668 0.507142857142857],...
    'String',{'Parameter error biases','the estimates of active deceleration'});

% Create textarrow
annotation(figure1,'textarrow',[0.528571428571424 0.392857142857143],...
    [0.595238095238101 0.733333333333333],...
    'String',{'Error only steps when','the vehicle actively decelerates'});
end